### PR TITLE
Fixes #12574 - Upgrade rubocop to 0.35.1

### PR DESCRIPTION
**Pull request by brandonweeks**
Same thing as theforeman/foreman#2924

### CODE REVIEW

**Comment by domcleal** [comment]
The rubocop test is failing as it seems to be crashing on one of our source files.  I think it should be filed as a bug against rubocop, and then we can either workaround it by excluding the code with a rubocop comment or config file.

<pre>
An error occurred while Style/StabbyLambdaParentheses cop was inspecting /home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/class_scanner_eparser.rb.
undefined method `children' for :do_find:Symbol
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:98:in `args?'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:83:in `lambda_with_args?'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/rubocop-0.35.1/lib/rubocop/cop/style/stabby_lambda_parentheses.rb:27:in `on_send'
</pre>

Edit: seems it's interpreting our `o.lambda` call as a lambda, this test shows it: https://gist.github.com/e792c526eed7275f6b4b

**Comment by brandonweeks** [comment]
Filed as bbatsov/rubocop#2451.

**Comment by brandonweeks** [comment]
> # rubocop:disable Style/StabbyLambdaParentheses 

doesn't work in this case, it still errs. disabled in `.rubocop.yml` instead.

**Comment by dmitri-d** [comment]
Merged in 45ba025. Thanks, @brandonweeks!

**Pull request closed without merging**
