### PR TITLE
fixes #7225: logger is now being correctly initialized during launch

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by lzap** [comment]
I am still not sure if this works as expected. If I add this line to the logger initialization method:

```
puts "****************** Initialized Logger *************************"
```

So the code looks like:

```
    def self.logger
      # We keep the last 6 10MB log files
      puts "****************** Initialized Logger *************************"
      logger = ::Logger.new(::Proxy::SETTINGS.log_file, 6, 1024*1024*10)
      logger.level = ::Logger.const_get(::Proxy::SETTINGS.log_level.upcase)
      logger
    end
```

Then I see the logger to be initialized twice during start and then every single request once. I'd expect this to be only initialized once and then never. What I am worried about is writing concurrently there. Here is what I see:

```
****************** Initialized Logger *************************
****************** Initialized Logger *************************
W, [2014-08-25T13:04:10.246038 #21166]  WARN -- : Couldn't find settings file /home/lzap/work/smart-proxy/config/settings.d/foreman_proxy.yml. Using default settings.
I, [2014-08-25T13:04:10.246194 #21166]  INFO -- : 'foreman_proxy' settings were initialized with default values: :enabled: true
W, [2014-08-25T13:04:10.246344 #21166]  WARN -- : Couldn't find settings file /home/lzap/work/smart-proxy/config/settings.d/facts.yml. Using default settings.
I, [2014-08-25T13:04:10.246436 #21166]  INFO -- : 'facts' settings were initialized with default values: :enabled: true
I, [2014-08-25T13:04:10.247123 #21166]  INFO -- : 'dhcp' settings were initialized with default values: :dhcp_provider: isc
I, [2014-08-25T13:04:10.247346 #21166]  INFO -- : 'puppetca' module is disabled.
I, [2014-08-25T13:04:10.247670 #21166]  INFO -- : 'puppet' settings were initialized with default values: :puppet_provider: puppetrun, :puppetdir: /etc/puppet
I, [2014-08-25T13:04:10.625089 #21166]  INFO -- : 'bmc' module is disabled.
I, [2014-08-25T13:04:10.625293 #21166]  INFO -- : 'chefproxy' module is disabled.
I, [2014-08-25T13:04:10.625528 #21166]  INFO -- : 'realm' module is disabled.
W, [2014-08-25T13:04:10.776553 #21166]  WARN -- : Missing SSL setup, https is disabled.
[2014-08-25 13:04:10] INFO  WEBrick 1.3.1
[2014-08-25 13:04:10] INFO  ruby 2.1.0 (2013-12-25) [x86_64-linux]
[2014-08-25 13:04:10] INFO  WEBrick::HTTPServer#start: pid=21166 port=8443
****************** Initialized Logger *************************
::1 - - [25/Aug/2014 13:04:33] "GET /features HTTP/1.1" 200 38 0.0070
localhost - - [25/Aug/2014:13:04:33 CEST] "GET /features HTTP/1.1" 200 38
- -> /features
****************** Initialized Logger *************************
::1 - - [25/Aug/2014 13:04:38] "GET /features HTTP/1.1" 200 38 0.0007
localhost - - [25/Aug/2014:13:04:38 CEST] "GET /features HTTP/1.1" 200 38
- -> /features
****************** Initialized Logger *************************
::1 - - [25/Aug/2014 13:04:39] "GET /features HTTP/1.1" 200 38 0.0007
localhost - - [25/Aug/2014:13:04:39 CEST] "GET /features HTTP/1.1" 200 38
- -> /features
```

**Comment by lzap** [comment]
I think the module instance method `logger` is never used, we should merge those into one method call making it a singleton.

**Comment by lzap** [comment]
Also second concern - I see that the logger initialization code expects SETTINGS to be available but I remember settings loaders to log some information:

```
W, [2014-08-25T13:04:10.246038 #21166]  WARN -- : Couldn't find settings file /home/lzap/work/smart-proxy/config/settings.d/foreman_proxy.yml. Using default settings.
I, [2014-08-25T13:04:10.246194 #21166]  INFO -- : 'foreman_proxy' settings were initialized with default values: :enabled: true
W, [2014-08-25T13:04:10.246344 #21166]  WARN -- : Couldn't find settings file /home/lzap/work/smart-proxy/config/settings.d/facts.yml. Using default settings.
I, [2014-08-25T13:04:10.246436 #21166]  INFO -- : 'facts' settings were initialized with default values: :enabled: true
I, [2014-08-25T13:04:10.247123 #21166]  INFO -- : 'dhcp' settings were initialized with default values: :dhcp_provider: isc
I, [2014-08-25T13:04:10.247346 #21166]  INFO -- : 'puppetca' module is disabled.
I, [2014-08-25T13:04:10.247670 #21166]  INFO -- : 'puppet' settings were initialized with default values: :puppet_provider: puppetrun, :puppetdir: /etc/puppet
I, [2014-08-25T13:04:10.625089 #21166]  INFO -- : 'bmc' module is disabled.
I, [2014-08-25T13:04:10.625293 #21166]  INFO -- : 'chefproxy' module is disabled.
I, [2014-08-25T13:04:10.625528 #21166]  INFO -- : 'realm' module is disabled.
W, [2014-08-25T13:04:10.776553 #21166]  WARN -- : Missing SSL setup, https is disabled.
```

Not sure if we have chicken`n`egg problem. In the ideal state, things are at least logged through the logger interface to the STDOUT/STDERR until it is properly configured.

**Comment by dmitri-d** [comment]
re: multiple initializations: the second will be gone once we resolve https://github.com/theforeman/smart-proxy/pull/205 (one way or another). Per-request instantiation is gone now (although I don't think there were any concurrency issues around that, will confirm).

Proxy::Log.logger is being used at https://github.com/witlessbird/smart-proxy/blob/logger-init-7225/lib/proxy/log.rb#L10

Proxy::Log#logger is only being used in Proxy::Setting during plugin settings loading, at which point logger is initialized. Proxy::Log relies on global settings, which do not use logger.

**Comment by dmitri-d** [comment]
re: multiple Logger instances -- ruby's logger will open LogDevice per instance with File::WRONLY | File::APPEND mode. So, while the logged order of events might differ from actual, they are not going to be lost...

**Comment by lzap** [comment]
Ok this looks fine. Thanks!

Merged as 915c16d for Foreman 1.7, thanks.

**Pull request closed without merging**
