### PR TITLE
Fixes #1225 - Added AWS DNS Provider

### PR DESCRIPTION
**Pull request by solcates**
Added feature 1225 - AWS DNS Provider for smart-proxy.

### CODE REVIEW

**Comment by solcates** [comment]
BTW, I meant to give credit to Daniel Maraio for the original hamfisting of the AWS provider on http://projects.theforeman.org/issues/1225.  It was a great starting point.

**Comment by shawnlopresto** [comment]
Just tried running this on Foreman 1.7 on CentOS 7 (ruby 2.0), but looks like the new aws class isn't being recognized.

E, [2015-03-06T20:10:53.749936 #14065] ERROR -- : undefined method `[]' for nil:NilClass
D, [2015-03-06T20:10:53.750135 #14065] DEBUG -- : /usr/share/foreman-proxy/modules/dns/providers/aws.rb:23:in`create'
/usr/share/foreman-proxy/modules/dns/dns_api.rb:54:in `block in class:Api'

Im trying to sort out myself, but being a ruby newbie' posting here, case you may be able to spot.

**Comment by shawnlopresto** [comment]
Is the line, 'authorize_with_ssl_client', necessary? I had to remove it, else I get the following thrown when restarting the proxy.

ERROR -- : Unable to access the SSL keys. Are the values correct in settings.yml and do permissions allow reading?: undefined local variable or method `authorize_with_ssl_client' for Proxy::Dns::Api:Class

**Comment by mmoll** [comment]
`authorize_with_ssl_client` is only for 1.8+ (which this PR is against), so that's normal.

**Comment by dmitri-d** [comment]
@solcates: there's a PR that changes the way DNS providers are implemented: https://github.com/theforeman/smart-proxy/pull/256. It hasn't been merged yet, but I don't expect huge changes there. Any chance you could port this to the new provider model? Shout if you need help with that...

**Comment by shawnlopresto** [comment]
My 'ERROR -- : undefined method []' for nil:NilClass' error turned out to be 'insufficient credentials'. May be a good idea to catch that error, case it happens. Both creation and deletion work great. Thanks so much.

**Comment by solcates** [comment]
@witlessbird I saw that was coming right after i put my PR together :)  I haven't had the time to look at how it will be effected.  I'll take a look tonight.

**Comment by solcates** [comment]
@tuxtek good catch, i'll catch that exception, and add it to the PR.

**Comment by solcates** [comment]
@witlessbird Not sure on etiquette here.  Would you prefer the porting prior to #256 or after it's merged?  seems like some simple path changes and a few tweaks would be needed, but not much.

**Comment by dmitri-d** [comment]
@solcates: My preference (admittedly I'm biased) would be to port your changes to https://github.com/theforeman/smart-proxy/pull/256 -- slightly less work porting the changes (compared to doing this afterwards) and another pair of eyes on the PR.

**Comment by dmitri-d** [comment]
[test]

**Comment by solcates** [comment]
@witlessbird Sounds good. i'll try to get it committed later today.

**Comment by solcates** [comment]
@witlessbird Well, you can tell i'm not the best at git PR's... trying to figure out how to add to PR #256.  I pulled it, added my changes, and tried to push back to the dns-providers branch on your fork.  No bueno, as i don't have rights to your fork.  What's the best way for me to get it into that PR?  create a new PR on my fork?
Sorry for the novice question, but i haven't tried to contribute to another's PR before.

**Comment by dmitri-d** [comment]
@solcates: you should be able to do a PR for the branch I used to create https://github.com/theforeman/smart-proxy/pull/256. Lemme know if you need a hand with that.

**Comment by dLobatog** [comment]
@solcates Mind to rebase? One of the commits in this PR got merged and it seems like it put the rest out of date

**Comment by domcleal** [comment]
@eLobato wouldn't it be better to wait for completion of #256?

**Comment by dmitri-d** [comment]
@eLobato: waiting for #256 would be my preference too.

**Comment by domcleal** [comment]
Hey @solcates.  First, thanks for the raising this PR and getting some attention on this area.  Since #256 got merged today, I've taken your patch and made a new DNS provider plugin out of it based on the new support we have for these.

You'll find it over at https://github.com/theforeman/smart_proxy_dns_route53 and it seems to work OK here for forward DNS entries.  If you'd like to continue being involved with it, I've love some help and will be trying to release and package it soon, once the couple of issues I've identified (and logged there) are resolved.

I hope that works for you, so I'll close this PR now, and thanks again for the feature!

**Pull request closed without merging**
