### PR TITLE
Fixes #25267 - Provide Ruby logger API method formatter

### PR DESCRIPTION
**Pull request by lzap**
This puts back method `formatter` which disappeared since the logging stack is no longer Ruby logger but logging gem which does not implement it. Dynflow requires this method to be present, blocker for 1.20 release @tbrisker.

### CODE REVIEW

**Review by iNecas — APPROVED** [review]
I can confirm this solves the issue for me

**Comment by tbrisker** [comment]
I am not familiar with this are so i'll take @iNecas's word on it, i'm fine pulling this into 1.20.

**Comment by tbrisker** [comment]
:cherries: to 1.20 as ad1f7fb

**Comment by lzap** [comment]
So @dLobatog made a good point that this is only an issue in dev setup, but it is worth cherry picking for sure, thanks all!

**Comment by iNecas** [comment]
Not completely true: it's also influencing debian quite a lot (as we use the dynflow-in-proxy version as well)

**Pull request merged**
