### PR TITLE
refs #12715 - update default values of log_buffer settings

### PR DESCRIPTION
**Pull request by domcleal**
Removed log_buffer_level from default settings as it appears to be
unused.

### CODE REVIEW

**Comment by ohadlevy** [comment]
@lzap can you review please?

**Comment by dmitri-d** [comment]
lgtm, thanks for catching extraneous log_buffer_level setting.

**Comment by dLobatog** [comment]
Merged as 02f993f6d1caa742811d47d83f34dfa96d32437f, thanks @domcleal!

**Comment by lzap** [comment]
Oh I just noticed, :+1:

**Pull request closed without merging**
