### PR TITLE
Allow the DNS smart-proxy to manage CNAME's

### PR DESCRIPTION
**Pull request by jgmchan**
This is a very simple change to the DNS smart proxy so it can support DNS CNAME's.

I would love to take a crack at implementing the version 2.0 DNS API for the proxy but this should get things to work for the time being.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by lzap** [comment]
Thanks. We would live to see SRV type too :-P Tests failed, resubmitting: [test]

**Comment by jgmchan** [comment]
Yeah, I think the smart-proxy should be able to handle a whole bunch of records. When I get the time I'm going to try and implement that v2 API :)

**Comment by lzap** [comment]
Ping - mind fixing tests?

**Comment by dmitri-d** [comment]
Closing this in favour of https://github.com/theforeman/smart-proxy/pull/436.

**Pull request closed without merging**
