### PR TITLE
Fixes #7749 - allow using logger in log_halt helper

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
dimatha reports a successful test via IRC.  I'd like to know when this broke, so we can include it in 1.6.1 if necessary there.. I suspect though that it's develop-only.

**Comment by ares** [comment]
I think this got broken during modularization but only on old sinatra, or do you want me to find exact sinatra version?

**Comment by domcleal** [comment]
Nah, not worried about the sinatra version - I was more curious if it was broken in 1.6.0 or nightly only.  Don't worry, it'll go into 1.6.1.

**Comment by domcleal** [comment]
Thanks @ares, merged as 2fe082e.

**Pull request closed without merging**
