### PR TITLE
Fixes #12370 - proxy logs stacktrace on SIGTTIN

### PR DESCRIPTION
**Pull request by lzap**
Good for investigation of 100 % CPU load.

### CODE REVIEW

**Comment by dmitri-d** [comment]
@lzap: I could live with one signal handler defined in `Proxy::Launcher.launch`, but if we are going to add this (and we could implement a handler for SIGTERM similarly), I think we should refactor signal handlers into a dedicated module/class. I can do that tomorrow if you don't have time...

**Comment by lzap** [comment]
> @lzap: I could live with one signal handler defined in `Proxy::Launcher.launch`, but if we are going to add this (and we could implement a handler for SIGTERM similarly), I think we should refactor signal handlers into a dedicated module/class. I can do that tomorrow if you don't have time... 

Introduced new class, I am not going to work on SIGTERM in this ticket
tho. Tried to play with it for a while, but this deserves own ticket and
must be tested properly.

## 

Later,
 Lukas #lzap Zapletal

**Comment by lzap** [comment]
Pushed the forgotten file.

Also for discussion: Loggingg the stackstrace via logger does not work, so I need to use STDOUT. But in case syslog is configured (and this is now the default on RHEL6), the output might end up nowhere. In systemd environments, the stdout is automatically acquired and added to journal, but I am not sure in non-systemd environments. Do we want to reopen STDOUT and redirect it into logs?

**Comment by domcleal** [comment]
> But in case syslog is configured (and this is now the default on RHEL6)

What do you mean precisely about RHEL6?  A file logger is the default everywhere, AFAIK.

**Comment by lzap** [comment]
> > But in case syslog is configured (and this is now the default on RHEL6)
> 
> What do you mean precisely about RHEL6?  A file logger is the default everywhere, AFAIK.

I was under impression we changed that to SYSLOG once it was introduced,
but that's not the case I see.

## 

Later,
 Lukas #lzap Zapletal

**Comment by domcleal** [comment]
No, 335a1610 added the capability but didn't change the default behaviour.

**Comment by lzap** [comment]
> No, 335a1610 added the capability but didn't change the default behaviour.

Created http://projects.theforeman.org/issues/12402 for the record. I
don't think the time has come yet.

## 

Later,
 Lukas #lzap Zapletal

**Comment by dmitri-d** [comment]
merged in `2c40ea5`. Thanks, @lzap!

**Pull request closed without merging**
