### PR TITLE
Fixes #10098 - Change cmd.exe with the environment variable, update gem requirement on windows

### PR DESCRIPTION
**Pull request by claer**

### CODE REVIEW

**Comment by Reedler** [comment]
This worked for me! Thanks everyone!

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
@claer, @mchesler: could you test this one please?

**Comment by mchesler** [comment]
@witlessbird this works for me

**Comment by Reedler** [comment]
I spoke too soon. When I actually try to spin up a vm I get this. error: ERF12-6899 [ProxyAPI::ProxyException]: Unable to set DHCP entry ([RestClient::BadRequest]: 400 Bad Request) for proxy

**Comment by mchesler** [comment]
@Reedler can you change the log verbosity to DEBUG and attach a stack trace from the smart proxy?

**Comment by Reedler** [comment]
The specified option does not exist.

E, [2015-05-05T13:14:35.198869 #4388] ERROR -- : Unknown error while processing ''
D, [2015-05-05T13:14:35.198869 #4388] DEBUG -- : c:/foreman/modules/dhcp/providers/server/native_ms.rb:227:in `rescue in report'
c:/foreman/modules/dhcp/providers/server/native_ms.rb:204:in`report'
c:/foreman/modules/dhcp/providers/server/native_ms.rb:199:in `execute'
c:/foreman/modules/dhcp/providers/server/native_ms.rb:61:in`block in addRecord'
c:/foreman/modules/dhcp/providers/server/native_ms.rb:48:in `each'
c:/foreman/modules/dhcp/providers/server/native_ms.rb:48:in`addRecord'
c:/foreman/modules/dhcp/dhcp_api.rb:96:in `block in <class:DhcpApi>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`[]'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in`route_eval'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in`block in process_route'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`process_route'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in`block in dispatch!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in`dispatch!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
c:/foreman/lib/proxy/log.rb:35:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`block in call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in`block in call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in`call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in`service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
C:/Ruby193/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
10.1.8.19 - - [05/May/2015 13:14:35] "POST /dhcp/10.1.8.0 HTTP/1.1" 400 33 29.6099

**Comment by mchesler** [comment]
@Reedler I believe that's an unrelated error.  Did you add option 60 to the DHCP server as described in step 14 in the MS DHCP section at http://theforeman.org/manuals/1.8/index.html#4.3.5DHCP?

**Comment by Reedler** [comment]
We don't use PXE and it was working before without option 60.

**Comment by mchesler** [comment]
Does it start working again if you revert the change in this PR?

**Comment by Reedler** [comment]
It pulls an IP just fine in the network section of the vm build. Here's some more info.
I, [2015-05-05T13:14:35.198869 #4388]  INFO -- : Vendor class not found
E, [2015-05-05T13:14:35.198869 #4388] ERROR -- : Netsh failed:

**Comment by Reedler** [comment]
No still won't work.

**Comment by mchesler** [comment]
That implies that the issue you're having is unrelated to this PR

**Comment by Reedler** [comment]
@mchesler Everything worked fine before this upgrade. The proxy stopped pulling an IP after the foreman upgrade so I upgraded the proxy. After I used this patch it would finally pull an IP but errors out on the build.

**Comment by Reedler** [comment]
Nothing has changed on the DHCP server.

**Comment by Reedler** [comment]
E, [2015-05-05T13:51:33.691093 #3968] ERROR -- : Record 10.2.5.0/10.2.5.1 not found
10.2.5.19 - - [05/May/2015 13:51:33] "GET /dhcp/10.2.5.0/10.2.5.1 HTTP/1.1" 404 34 25.4372

**Comment by dmitri-d** [comment]
I'm closing this PR as ms dhcp provider has been completely rewritten and no longer relies on cmd.exe/netsh.

**Pull request closed without merging**
