### PR TITLE
Fixes #29430 - sync Rubocops to core config

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
@ehelms is close to merging https://github.com/theforeman/smart-proxy/pull/623, after that this can be merged.

**Comment by mmoll** [comment]
Rebased and including even more cops that are enabled in core.

**Comment by mmoll** [comment]
As GH-623 is postponed, could this get merged now?

**Comment by mmoll** [comment]
BTW, I'd be super-willing to do the Puma PR rebasing after this gets in. ;)

**Review by ekohl — APPROVED** [review]

**Pull request merged**
