### PR TITLE
fixes #7060: puppet gem is no longer required if puppetca is disabled.

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by lzap** [comment]
Going to test this now with discovery image: http://koji.katello.org/koji/taskinfo?taskID=139766

**Comment by lzap** [comment]
It works fine, verified on the disovery image.

Any chance getting this merged so I have it in tomorrows nightly and todays snap?

**Comment by dmitri-d** [comment]
merged in at ed3332a.

**Comment by GregSutcliffe** [comment]
@witlessbird don't merge your own PRs please - @lzap I thought you had merge rights, so you should have merged it if you were happy ;)

**Pull request closed without merging**
