### PR TITLE
Fixes #19599: del dhcp record returns empty body on success.

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by ekohl** [comment]
Should it also verify the HTTP status code? I'd expect a 204 No Content or 404 Not Found

**Comment by dmitri-d** [comment]
> Should it also verify the HTTP status code? I'd expect a 204 No Content or 404 Not Found

I think a 204 would be appropriate for the newly added calls. I also think it should be handled in a dedicated PR. The old (and deprecated) call should remain as it was before the regression this PR is addressing was introduced.

**Comment by ekohl** [comment]
Then maybe verify that it keeps returning HTTP 200 in the tests? There are frameworks out there (Django REST Framework) that automatically returns a HTTP 204 when the body is empty so a test to specify the behaviour would be nice.

**Comment by dmitri-d** [comment]
* updated dhcp api tests to check for 200 return status on delete record calls.

**Comment by domcleal** [comment]
> updated dhcp api tests to check for 200 return status on delete record calls.

I can't see this change, can you re-check please?

**Comment by dmitri-d** [comment]
Apologies, forgot to push.

**Review by ekohl — APPROVED** [review]

**Review by domcleal — APPROVED** [review]

**Comment by domcleal** [comment]
Thanks @witlessbird.

**Pull request merged**
