### PR TITLE
Fixes #21710 - correct arguments to find_free_ip are used.

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by ares** [comment]
rubocop is not happy about the change - http://ci.theforeman.org/job/test_proxy_develop_pr_rubocop/1126/checkstyleResult/new/

but it fixes the issue, so :+1: after fixing rubocop

**Comment by dmitri-d** [comment]
- fixed rubocop warnings.

**Comment by dmitri-d** [comment]
Test failures are due to newer rack and rack-test dependencies requiring ruby >= 2.2.2. The issue is resolved in https://github.com/theforeman/smart-proxy/pull/552

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
[test default]

**Comment by ares** [comment]
Thanks @witlessbird, merging!

**Pull request merged**
