### PR TITLE
Fixes #10259 - Templates are now correctly proxied

### PR DESCRIPTION
**Pull request by lzap**
I have amended my changes from the previous review: https://github.com/theforeman/smart-proxy/pull/279

### CODE REVIEW

**Comment by domcleal** [comment]
Foreman's API doesn't support MAC address lookup, that's only foreman_bootdisk, so I'm not sure this should be here.  The PR also cannot be merged.

**Comment by lzap** [comment]
Since this is a public API, I don't see particular reason why not to have it here. Amended.

**Comment by lzap** [comment]
I mean I don't see any issues with having it like this. Could create extra API tho.

**Comment by domcleal** [comment]
I'm not sure I understand your point?  MAC isn't an option supported by Foreman, so we shouldn't carry support in the smart proxy for it..

**Comment by lzap** [comment]
Oh now I understand. Foreman without bootdisk will not return the correct data to proxy, won't it?

**Comment by domcleal** [comment]
Right, Foreman without bootdisk doesn't look up a template with this parameter.

**Comment by lzap** [comment]
Ok, how about this: I add a parameter and this lookup will be turned off by default. Bootdisk users will be asked to turn this feature on here.

**Comment by domcleal** [comment]
I don't follow, an extra request parameter?

**Comment by dmitri-d** [comment]
I would very much like avoid a configurable API parameter. looking at the foreman side, the `mac` would be ignored in the absence of bootdisk. Could we put a comment next to https://github.com/theforeman/smart-proxy/pull/287/files#diff-40b456408d24baac53fa8e0cf3315631R14 saying that this is only available in the presence of bootdisk?

**Comment by lzap** [comment]
Yeah sorry I mean configuration option (settings.d/templates.yaml).

**Comment by lzap** [comment]
Added the comment...

**Comment by lzap** [comment]
I really don't know how to approach this to be honest other than explicitly disabling the feature via YAML settings. I can do some testing what happens when bootdisk is not installed, I'd expect just 404 which is not bad at all. We can maybe catch the exception if there is any and issue some proper error message.

**Comment by lzap** [comment]
For the record, we need this to enable the indirect communication patch for bootdisk: https://github.com/theforeman/foreman_bootdisk/pull/9

**Comment by dmitri-d** [comment]
@lzap, yeah, worth a test. I don't think anything will break and the 'mac' parameter will be ignored. I think.

**Comment by lzap** [comment]
Ok Foreman without Bootdisk returns 404:

```
2015-06-30 17:01:45 [app] [I] Started GET "/unattended/iPXE?url=http%3A%2F%2F192.168.122.1%3A8448" for 127.0.0.1 at 2015-06-30 17:01:45 +0200
2015-06-30 17:01:45 [app] [I] Processing by UnattendedController#iPXE as TEXT
2015-06-30 17:01:45 [app] [I]   Parameters: {"url"=>"http://192.168.122.1:8448", "unattended"=>{}}
2015-06-30 17:01:45 [app] [I] unattended: unable to find a host that matches the request from 127.0.0.1
2015-06-30 17:01:45 [app] [I] Filter chain halted as :get_host_details rendered or redirected
2015-06-30 17:01:45 [app] [I] Completed 404 Not Found in 109.2ms (ActiveRecord: 1.2ms)
```

Which is properly handled in proxy:

```
lzapx.brq.redhat.com - - [30/Jun/2015:17:01:45 CEST] "GET /unattended/iPXE?mac=52:54:00:da:75:61 HTTP/1.1" 500 213
- -> /unattended/iPXE?mac=52:54:00:da:75:61
```

**Comment by dmitri-d** [comment]
Alternatively you could create a dedicated smart-proxy module for this. On the foreman side you can either use a different pxe linux template (pointing to the new api end point) or override `default_template_url` helper.

**Comment by lzap** [comment]
That looks like total overrkill, how about this: I move the ability to search for a host by mac into Foreman Core? @domcleal

**Comment by lzap** [comment]
Ok I am closing this patch as it looks like generic proxying will be better. It will also help to solve problem when Anaconda http headers are currently not being handed over (I think).

**Pull request closed without merging**
