### PR TITLE
fixes #6275 - idempotence needs clone of original data and to handle *_port

### PR DESCRIPTION
**Pull request by domcleal**
@witlessbird, @GregSutcliffe if you can test & review asap, I'd like to merge this to avoid tripping people up

edit: fixed in packaging, not urgent now

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1: looks fine to me. I think it's important we get those port settings in.

**Comment by dmitri-d** [comment]
lgtm.

**Comment by GregSutcliffe** [comment]
@lzap can you merge please? @domcleal isn't going to merge his own PRs :P

**Comment by lzap** [comment]
Pushed as 14fc2ce, thanks @domcleal.

**Pull request closed without merging**
