### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ekohl**
This is mostly a PR to test the Jenkins job. Actual changes should also be done in develop.

### CODE REVIEW

**Comment by ekohl** [comment]
[test smart-proxy]

**Comment by ekohl** [comment]
[test smart-proxy]

**Comment by ekohl** [comment]
[test smart-proxy]

**Comment by ekohl** [comment]
[test smart-proxy]

**Comment by ekohl** [comment]
[test smart-proxy]

**Comment by ehelms** [comment]
[test smart-proxy]

**Pull request closed without merging**
