### PR TITLE
Fixes #37355 - Explicitly query for IPv4 address in omapi code

### PR DESCRIPTION
**Pull request by ekohl**
The omapi API is IPv4-only so the DNS lookup should also only ask for IPv4 addresses. Otherwise it may return an IPv6 address which ip2hex can't deal with.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
You need to adjust the tests/mocks, but otherwise LGTM

**Comment by ekohl** [comment]
Further interesting observation: if it's not resolved by the Smart Proxy, something else does. I didn't check if it's dhcpd or the client, but something resolved the address (which is ipv6-only). Then I can only assume the address is truncated to fit in ipv4. So you may see an unexpected value used for your tftp server

**Comment by evgeni** [comment]
[test smart-proxy]

**Comment by evgeni** [comment]
[test smart-proxy]

**Pull request merged**
