### PR TITLE
refs #5793 - add pkg:generate_source rake task to create tar.bz2

### PR DESCRIPTION
**Pull request by domcleal**
Will resubmit to all core projects soon, to produce a standard way of creating package "sources".

### CODE REVIEW

**Comment by dmitri-d** [comment]
seems to be working, lgtm!

**Comment by lzap** [comment]
it works fine, but can we make the lengthy `pkg:generate_source` as a default task so it will work with this too:

```
rake pkg
```

+1 nice

**Comment by domcleal** [comment]
@lzap generally it's going to be for computers rather than us so I'm not too concerned about the length.. can do though.  I was trying to name it so it's unlikely to conflict with anything anybody else wants (e.g. foreman core already has pkg:deb).

**Comment by lzap** [comment]
Hmmm that's okay then. But we sometimes release tarballs, not quite
often.

LZ

On Fri, May 23, 2014 at 05:20:36AM -0700, Dominic Cleal wrote:

> @lzap generally it's going to be for computers rather than us so I'm not too concerned about the length.. can do though.  I was trying to name it so it's unlikely to conflict with anything anybody else wants (e.g. foreman core already has pkg:deb).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/smart-proxy/pull/159#issuecomment-44002369

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by GregSutcliffe** [comment]
:+1: I'd merge but I don't have commit-bit - someone should do the honours :)

**Comment by lzap** [comment]
Pushed as
- 9f019d1 refs #5793 - add pkg:generate_source rake task to create tar.bz2 <Dominic Cleal>

Thanks!

**Pull request closed without merging**
