### PR TITLE
Adding CNAME support in smart-proxy with nsupdate.

### PR DESCRIPTION
**Pull request by RodolpheFouquet**
Adding the CNAME support on the nsupdate DNS smart-proxy.

It checks if the DNS is not already bound. If so, it raises an exception.
Else, it adds a CNAME record for value => fqdn.

### CODE REVIEW

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
Thanks for the contribution!
- Could you create a ticket here http://projects.theforeman.org/projects/smart-proxy/issues explaining the issue, and change the commit message to 'Fixes #ticket_number_here: short explanation'. 
- Could you add a test?

**Comment by RodolpheFouquet** [comment]
Hi, sorry for the late response.

About the tests, I fail to understand which test I should implement in smart-proxy.

The tests does not seem to have been implemented within smart-proxy but in foreman (which is kinda weird).

Should I add a new one? 

About the ticker, there is already #551 which is referring to the CNAME support in smart proxy.

**Comment by logicminds** [comment]
You should add test cases that would exercise your code.  I see a minimum of four test cases.

**Comment by dmitri-d** [comment]
Internal api have changed since this PR was submitted and it will require changes to get it working. I'm closing this PR, please update the code in here to use the new internal api and re-submit it.

**Pull request closed without merging**
