### PR TITLE
support for IPv6 PTR

### PR DESCRIPTION
**Pull request by pencil**
This change allows the deletion of IPv6 PTR values

### CODE REVIEW

**Comment by ohadlevy** [comment]
looks simple enough, I don't have an ipv6 env to try it out, is that all it takes? - I heard ipv6 deployment are more complicated than that ;)

**Comment by pencil** [comment]
It's all it takes to delete an IPv6 PTR value. Creation already works out of the box. Don't be afraid of IPv6 ;)

http://www.sixxs.net/wiki/DNS_Configuration#Adding_your_own_IPv6_data

**Comment by luxflux** [comment]
Will you roll out a new version with this fix soon?

**Comment by ohadlevy** [comment]
You mean as a rpm? or a git tag?

**Comment by luxflux** [comment]
.deb packages would be cool :)

**Comment by ohadlevy** [comment]
I'm guessing the nightly packages would be available in a few hours :)

http://deb.theforeman.org

**Comment by luxflux** [comment]
Aw, I'm sorry. Totally forgot that there are nightly builds... What about the stable version? When do you plan to release 0.4? Just wondering...

**Comment by ohadlevy** [comment]
Hopefully within a month, let me know if you need it any earlier :)

**Pull request merged**
