### PR TITLE
Fixes #8347 - facts feature should not be enabled by default

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by lzap** [comment]
To give you some background - facts_api is only used on the discovery image, this should been turned off by default. Anyway, the plugin is not loaded when `facter` gem is missing.

LGTM except the bundler.d change, we don't need this for discovery I think. But if @domcleal don't mind adding this new group let's have it there (we will likely need a packaging change tho).

**Comment by dmitri-d** [comment]
The idea is to use the facter gem that is available on the system, not to install ours. Could you remove  `bundler.d/facts.rb`? Looks good otherwise.

**Comment by domcleal** [comment]
That's what bundler_ext is for, and this is the same pattern as in core.  It looks correct to me.

**Comment by orrabin** [comment]
@domcleal I removed `bundler.d/facts.rb` before seeing your comment.
@witlessbird what if facter gem isn't available on the system? shouldn't we install?

**Comment by dmitri-d** [comment]
If facter isn't available we don't load the plugin: https://github.com/theforeman/smart-proxy/blob/develop/modules/facts/facts_plugin.rb#L8

**Comment by lzap** [comment]
Yes @witlessbird is right, I forgot. Looks sane, thank you. Merging as fc67f91.

**Pull request closed without merging**
