### PR TITLE
Refs #34226 - dnscmd nil string error

### PR DESCRIPTION
**Pull request by lzap**
This is a third patch, hopefully a last one. I am keeping this as a Draft until the user confirms it works fine.

Then I will backport no. 2 and 3 into the stable release.

Again: This is untested, I don't have dnscmd setup.

### CODE REVIEW

**Comment by lzap** [comment]
Confirmed to be working, tested by the user. Let's merge and I will backport both the fixes to 3.1.

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Looks like Rubocop is unhappy, other than that :+1:

**Comment by lzap** [comment]
Yeah this is where my terminal wrapped, I remember I was counting key presses to get it right. Well, did not do it. Should be fixed now.

Merging, backporting both into 3.1. Thanks.

**Comment by lzap** [comment]
Backporting everyrhing:

* 7b3508a8444c04148f6c99f426a5de5d805f99a6
* f88024edf5f24f92a0b7ab98d64b58e4b61e3e4c
* 23bb5a07c694388ff05213b3a5b30c015c11ecf4

https://github.com/theforeman/smart-proxy/pull/815

**Pull request merged**
