### PR TITLE
fixes #6542 - ship freeipa script for creating users

### PR DESCRIPTION
**Pull request by stbenjam**
Should have done this originally, but now there's conversations downstream about shipping it instead of having users copy + paste from docs.

### CODE REVIEW

**Comment by domcleal** [comment]
Could you also propose a change to foreman-packaging rpm/develop (and deb/develop if you're feeling up to it, and/or with @GregSutcliffe's help) to install it to a sensible location?

**Comment by stbenjam** [comment]
@domcleal What's a sensible location for you? 

I'd keep it in extra/ or is /usr/bin better? Maybe name it foreman-prepare-realm (in case sometime in the future it needs to do something for active directory, too).

**Comment by domcleal** [comment]
I think /usr/sbin would be best, and I like your name suggestion.  We should avoid having scripts in /usr/share (outside of doc/) that users are meant to execute IMO.

**Comment by GregSutcliffe** [comment]
+1 that'll work for deb too.

**Comment by dLobatog** [comment]
Tested, works :ok: 

``` bash
Password for admin@LOCALDOMAIN: 
---------------------------------------
Added permission "modify host password"
---------------------------------------
  Permission name: modify host password
  Permissions: write
  Attributes: userpassword
  Type: host
-----------------------------------------
Added permission "write host certificate"
-----------------------------------------
  Permission name: write host certificate
  Permissions: write
  Attributes: usercertificate
  Type: host
----------------------------------------
Added permission "modify host userclass"
----------------------------------------
  Permission name: modify host userclass
  Permissions: write
  Attributes: userclass
  Type: host
---------------------------------------------
Added privilege "Smart Proxy Host Management"
---------------------------------------------
  Privilege name: Smart Proxy Host Management
  Description: Smart Proxy Host Management
  Privilege name: Smart Proxy Host Management
  Description: Smart Proxy Host Management
  Permissions: add hosts, remove hosts, modify hosts, modify services, manage host keytab, manage
               service keytab, retrieve certificates from the ca, revoke certificate, modify host
               password, write host certificate, modify host userclass
  Failed members: 
    permission: read dns entries: permission not found
    permission: remove dns entries: permission not found
    permission: add dns entries: permission not found
    permission: update dns entries: permission not found
------------------------------
Number of permissions added 11
------------------------------
-------------------------------------
Added role "Smart Proxy Host Manager"
-------------------------------------
  Role name: Smart Proxy Host Manager
  Description: Smart Proxy management
  Role name: Smart Proxy Host Manager
  Description: Smart Proxy management
  Privileges: Smart Proxy Host Management
----------------------------
Number of privileges added 1
----------------------------
ipa: ERROR: invalid 'email': invalid e-mail format: admin@localdomain
  Role name: Smart Proxy Host Manager
  Description: Smart Proxy management
  Member users: admin
  Privileges: Smart Proxy Host Management
-------------------------
Number of members added 1
-------------------------
Keytab successfully retrieved and stored in: freeipa.keytab
Realm Proxy User:    admin
Realm Proxy Keytab:  /root/freeipa.keytab
```

**Comment by stbenjam** [comment]
@eLobato Just curious, what version of IPA did you use there? It's missing the DNS roles.

**Comment by stbenjam** [comment]
@eLobato Oh nevermind, it doesn't create them if you didn't install with `--setup-dns`

**Comment by dLobatog** [comment]
Right, it's FreeIPA 3.3.0 for the record.

On Tue, Jul 22, 2014 at 12:46 PM, Stephen Benjamin <notifications@github.com

> wrote:
> 
> @eLobato https://github.com/eLobato Oh nevermind, it doesn't create
> them if you didn't install with --setup-dns
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theforeman/smart-proxy/pull/184#issuecomment-49723570
> .

## 

Daniel Lobato

@elobatoss
blog.daniellobato.me
daniellobato.me

GPG: http://keys.gnupg.net/pks/lookup?op=get&search=0x7A92D6DD38D6DE30

**Comment by domcleal** [comment]
Thanks @stbenjam, merged as c54e833 for Foreman 1.6.

**Pull request closed without merging**
