### PR TITLE
Fixes #12012: missing puppet module dependencies no longer crash smart-proxy on startup

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks sane on review, if someone could give it a quick test...

**Comment by helge000** [comment]
@witlessbird : tested this; solves the issue with me

**Comment by GregSutcliffe** [comment]
Merged as 175da54, thanks @witlessbird and @helge000!

**Comment by lzap** [comment]
This patch did not solve the problem on discovery image. Tested version is: http://yum.theforeman.org/nightly/el7/x86_64/foreman-proxy-1.10.0-0.develop.201510011101git175da54.el7.noarch.rpm

Screenshot of the stack trace:

smart-proxy_2015-10-02_10 26 07

**Comment by lzap** [comment]
For the record it says "cannot load such file: 'puppet'"

**Comment by dmitri-d** [comment]
The discovery image from the screenshot above isn't using smart-proxy with this PR. `require 'puppet_proxy/initializer'` that's crashing it is on line 1 of `puppet_plugin.rb`. Here's the version of puppet_plugin.rb with these changes applied: https://github.com/theforeman/smart-proxy/blob/develop/modules/puppet_proxy/puppet_plugin.rb#L14

**Comment by lzap** [comment]
Had to boot a wrong image, it does work now.

**Pull request closed without merging**
