### PR TITLE
fixes #15985 - Pxegrub2 tftp filename prefix

### PR DESCRIPTION
**Pull request by timogoebel**
@lzap : Mind to take a look?

### CODE REVIEW

**Comment by lzap** [comment]
I will test this with Grub2 from RHEL7, maybe it was patched and starting with MAC without 01, I was testing all my entries in the design table.

**Comment by timogoebel** [comment]
> I will test this with Grub2 from RHEL7

Thanks. That's what I also tested this with. I also found this in some SUSE, Oracle and some other distro's documentation.

**Comment by lzap** [comment]
I can confirm this now. Thanks.

**Comment by lzap** [comment]
Merged as d4b60b36842ce5203cc009863ef89e21d71176b5, thank you!

**Pull request closed without merging**
