### PR TITLE
Fixes #2119 - Properly support colon-separated modulepath

### PR DESCRIPTION
**Pull request by GregSutcliffe**
We were not properly handling module paths with colons in. Due to a bad regex (/\$environment.*/,'/') the secondary paths are dropped, and then lost when Dir can't find the first parent.

Best viewed with ?w=1 as indentation has changed ;)

### CODE REVIEW

**Comment by ohadlevy** [comment]
looks ok, but would need a test imho :)

**Comment by GregSutcliffe** [comment]
@ohadlevy done - thanks for reminding me. In writing the test I found that my fix didn't work in all cases - this should be much better ;)

**Comment by GregSutcliffe** [comment]
Hang on, it's still not quite right. More tests incoming.

**Comment by GregSutcliffe** [comment]
@ohadlevy ok added _a lot_ more tests; there are so many environment corner-cases ;)

I had to move/add some fixtures so that some of the `$environment` code could be properly tested.

**Comment by GregSutcliffe** [comment]
Pushed fix for array-sorting test errors.

**Comment by ohadlevy** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @GregSutcliffe!  Hairy code indeed.  Merged as 722bba.

**Pull request closed without merging**
