### PR TITLE
Fixes #20236 - Unify DNS record conflict detection

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
what's the status here?

**Comment by dmitri-d** [comment]
@ekohl: ping

**Comment by ekohl** [comment]
I haven't really looked at this in a while. @witlessbird is this something that you think is a good improvement? Then I'll rebase this and make the tests pass.

**Comment by dmitri-d** [comment]
I think your changes make a better factored code, so if you have time please rebase/update this PR.

**Comment by dmitri-d** [comment]
Merged. Thanks, @ekohl.

**Pull request merged**
