### PR TITLE
Fixes #19709 - check version before loading dependencies.

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
This is improve reporting of loading errors that can happen due to changes in core/core modules between different versions of smart-proxy.

**Comment by dmitri-d** [comment]
[test]

**Review by dLobatog — COMMENTED** [review]
@witlessbird How can I reproduce this?

**Comment by dmitri-d** [comment]
@dLobatog: to see the issue: try using latest dhcp_isc_remote provider with proxy v1.15. To verify the fix works under 1.16 you'll need to modify one of non-core providers (change the required proxy version).

**Review by dLobatog — APPROVED** [review]

**Comment by dLobatog** [comment]
Works fine, thanks @witlessbird !

**Pull request merged**
