### PR TITLE
Fixes #8320 - shutdown shell provider concurrency issue

### PR DESCRIPTION
**Pull request by lzap**
Unfortunately the `shutdown` command does not support finer granularity than
minutes. So we will waste one minute everytime here. Better ideas?

We need to make sure the response gets returned back. Maybe to spawn a shell
with sleep 5s && shutdown...

### CODE REVIEW

**Comment by lzap** [comment]
Ok after some time playing with a shell wrapper, I found that the most reliable way is to actually spawn new thread, let the Sinatra to finish the request (giving it 5 seconds grace period) and calling shutdown normally.

**Comment by lzap** [comment]
Testers wanted, now, who wants to reboot the dev machine, huh? ;-)

**Comment by lzap** [comment]
Tip for reviewer: To test this, use this command: `curl -3 -H "Accept:application/json" -H "Content-Length:0" -k -X PUT http://192.168.122.52:8443/bmc/ignored/chassis/power/cycle`

**Comment by dmitri-d** [comment]
lgtm.

**Comment by dmitri-d** [comment]
merged at 81c679e. Thanks, @lzap!

**Pull request closed without merging**
