### PR TITLE
Fixes #6022 - disable StrictHostKeyChecking

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
Should this be configurable?

**Comment by mmoll** [comment]
Unsure, I guess at least the default of disabling the checking makes things much easier for the people using puppetrun with ssh.

**Comment by lzap** [comment]
I tend to agree with @ekohl having this configurable is not a huge change and benefit is big. On the other hand, this is doable in `/etc/ssh/ssh_config` but I still find it useful to have it here as a sane default rather than puppetizing another file.

**Comment by dmitri-d** [comment]
I'm on a fence re: configuration option. It's probably not that useful as a security measure for puppet-managed hosts...

**Comment by mmoll** [comment]
so...?

**Comment by dmitri-d** [comment]
My vote would be for not having a configurable 'StrictHostKeyChecking' option, at least at first. Unless everyone else is feeling strongly about this...

**Comment by lzap** [comment]
I am fine with that.

**Comment by lzap** [comment]
Thanks.

**Pull request merged**
