### PR TITLE
Fixes #18149 - Duplicates due to OU in certnames

### PR DESCRIPTION
**Pull request by ananace**

### CODE REVIEW

**Comment by dmitri-d** [comment]
Thanks for the PR. Could you add a test (here: https://github.com/theforeman/smart-proxy/blob/develop/test/puppetca/puppetca_test.rb) to verify CN parsing?

**Comment by ananace** [comment]
Since there was already a test for inventory parsing, I decided to extend it with one entry containing an OU.

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
Merged in 5bef03a. Thanks, @ace13!

**Pull request closed without merging**
