### PR TITLE
Refs #12209: Pass in the actual values to remove_ptr_record

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
cc @helge000

**Comment by helge000** [comment]
I already did that using the same PTRs; any of us should be able rebase

**Comment by dmitri-d** [comment]
@ekohl: could you rebase this --  https://github.com/theforeman/smart-proxy/commit/450e0b694ead84961db9c1ffd4256919423484f6 fixed issues in dnscmd tests, but nsupdate-related tests need your fixes.

**Comment by ekohl** [comment]
Rebased

**Comment by dmitri-d** [comment]
create PTR record tests are wrong too -- `create_ptr_record` will received a reversed address as a parameter, `nsupdate` expects reversed address as well.

**Comment by ekohl** [comment]
> create PTR record tests are wrong too -- create_ptr_record will received a reversed address as a parameter, nsupdate expects reversed address as well.

You may be right here and I may have a bug in smart_proxy_dns_powerdns.

**Comment by ekohl** [comment]
Updated

**Comment by ekohl** [comment]
I can't explain that one test failure.

**Comment by dmitri-d** [comment]
An intermittent issue when resolving rubygems.org. [test]

**Comment by ekohl** [comment]
They're green now

**Comment by dmitri-d** [comment]
Merged in at c1994b8. Thanks, @ekohl!

**Pull request closed without merging**
