### PR TITLE
Fixes #17843 - Added a cross platform 'which' for the nsupdate

### PR DESCRIPTION
**Pull request by alex131290**

### CODE REVIEW

**Comment by mmoll** [comment]
@alex131290 which platfrom are you running the proxy on, that the current approach fails?

**Comment by alex131290** [comment]
@mmoll  I'm running it on Windows Server 2012

**Comment by dmitri-d** [comment]
Is this related to http://projects.theforeman.org/issues/17823? If so, any reason you aren't using dns_dnscmd provider, which is the MS specific one?

**Comment by alex131290** [comment]
@witlessbird It's not related to it, it's just another bug that i found while i was testing both tools (nsupdate and dnscmd) on Windows Server.
I'd be grateful if you can take a look at  http://projects.theforeman.org/issues/17823

**Comment by alex131290** [comment]
Guys, any updates on this one?

**Comment by ekohl** [comment]
Since ```which``` is defined in ```lib/proxy/util.rb```, would it make sense to change it there?

**Comment by mmoll** [comment]
what's the status here?

**Comment by lzap** [comment]
Thanks for the patch, I don't understand how nsupdate is useful on Windows platform. Please explain and reopen if you want to push this forward.

**Pull request closed without merging**
