### PR TITLE
Fixes #35979 - dnscmd nil string error

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
This fixes: https://community.theforeman.org/t/windows-dns-smart-proxy-does-not-delete-a-records/31105/8

Without this change, the following happen:
```
 49 2023-01-23T13:42:52 6cdc8631 [D] executing: ["c:\\Windows\\System32\\dnscmd.exe", "prox.atix", "/EnumRecords", "10.168.192.in-addr.arpa", "10.166.168.192.in-addr.arpa.", "/Type", "PTR"]
 50 2023-01-23T13:42:52 6cdc8631 [E] Command dnscmd failed:
 51 
 52 
 53 DNS Server failed to enumerate records for node 141.10.168.192.in-addr.arpa..
 54 
 55     Status = 9714 (0x000025f2)
 56 
 57 Command failed:  DNS_ERROR_NAME_DOES_NOT_EXIST     9714    0x25F2
 58 
 59 
 60 
 61 2023-01-23T13:42:52 6cdc8631 [E] Command dnscmd failed:
 62 
 63 
 64 DNS Server failed to enumerate records for node 10.166.168.192.in-addr.arpa..
 65 
 66     Status = 9714 (0x000025f2)
 67 
 68 Command failed:  DNS_ERROR_NAME_DOES_NOT_EXIST     9714    0x25F2
 69 
 70 
 71 
 72 2023-01-23T13:42:52 6cdc8631 [E] Unknown error while processing ''
 73 2023-01-23T13:42:52 6cdc8631 [W] Error details for Unknown error while processing '': <Proxy::Dns::Error>: Unknown error while processing ''
 74 C:/smart-proxy/modules/dns_dnscmd/dns_dnscmd_main.rb:76:in `rescue in report'
 75 C:/smart-proxy/modules/dns_dnscmd/dns_dnscmd_main.rb:57:in `report'
```

**Review by ekohl — APPROVED** [review]
From reading the code (I don't have access to a Windows machine) this looks correct. I verified that after this patch all calls to `execute` pass the `msg` argument:
```console
$ rg execute modules/dns_dnscmd/
modules/dns_dnscmd/dns_dnscmd_main.rb
17:      execute("/RecordAdd", zone, "#{name}.", type, value, msg: msg, error_only: false)
23:      execute("/RecordDelete", zone_name, "#{node_name}.", type, record, "/f", msg: msg, error_only: false)
35:    def execute(*args, **keyword_args)
101:      response = execute '/EnumZones', msg: 'EnumZones', error_only: true
112:      response = execute "/EnumRecords", zone_name, "#{node_name}.", "/Type", type, msg: 'EnumRecords', error_only: true
```

**Comment by ekohl** [comment]
Oh, too soon. The only thing is that you can't use `Refs` on an already released Redmine issue. You should open a new one that links to the one you have. Otherwise it won't show up in the changelog and it makes cherry picks hard.

Test failures are also related.

**Review by ekohl — APPROVED** [review]
Thanks for the quick update.

**Comment by mfuhrmann** [comment]
@ekohl When will this fix be available? Or in which version?

**Comment by ekohl** [comment]
https://projects.theforeman.org/issues/35979 has  a field "Fixed in releases" which tells you the version(s) that include the fix. Right now that's only 3.6.0. I don't think we're planning a 3.5.5 release given where we are with Foreman 3.7. Does that answer your question?

**Pull request merged**
