### PR TITLE
Fixes #12138 Add require statements

### PR DESCRIPTION
**Pull request by ekohl**
Adding these allows smart_proxy to be run from bundler.

### CODE REVIEW

**Comment by ekohl** [comment]
I still have some issues. In particular the `require 'rake'` in the gemspec doesn't work on ruby 1.8.7. I also wonder why `s.default_executable = 'bin/smart_proxy.rb'` is there since that file doesn't exist.

**Comment by domcleal** [comment]
> In particular the require 'rake' in the gemspec

I can't see why it'd be needed anyway, remove it?

**Comment by dmitri-d** [comment]
@ekohl: could you file a ticket and explain the problem in there? At the moment  https://github.com/theforeman/smart-proxy/blob/develop/lib/smart_proxy.rb#L31 loads main dependencies which include rack and sinatra, and should be sufficient.

**Comment by ekohl** [comment]
I created http://projects.theforeman.org/issues/12138 and will update the commit once I know what the correct solution is.

**Comment by dmitri-d** [comment]
@ekohl: After thinking about this, I realised that your approach is a good way to resolve the issue. Could you add requires for 'json', 'sinatra', and 'rack' somewhere around here: https://github.com/theforeman/smart-proxy/pull/323/files#diff-283e99ae18637863a4569b30d7d62f7eR30 and https://github.com/theforeman/smart-proxy/blob/develop/lib/smart_proxy_for_testing.rb#L3. I'll clean up `Gemfile` and gemspec in a seprate PR.

**Comment by dmitri-d** [comment]
@ekohl: or were you asking about https://github.com/theforeman/smart-proxy/pull/323/files#diff-283e99ae18637863a4569b30d7d62f7eR30?

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
@ekohl: ping?

**Comment by ekohl** [comment]
@witlessbird something like this?

**Comment by dmitri-d** [comment]
merged in at c9f0a07. Thanks, @ekohl!

**Pull request closed without merging**
