### PR TITLE
Fixes #10320 - WIN32 requires additional gems

### PR DESCRIPTION
**Pull request by mchesler**

### CODE REVIEW

**Comment by dmitri-d** [comment]
@claer: could you test this?

**Comment by dmitri-d** [comment]
[test]

**Comment by claer** [comment]
Works for me :)

**Comment by dmitri-d** [comment]
merged in at 418d1b7. Thanks, @mchesler!

**Comment by mchesler** [comment]
Happy to help @witlessbird.  Thanks for getting the change merged in.

**Pull request closed without merging**
