### PR TITLE
Fixes #22496 - use common free_ips code in ms dhcp provider

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Review by lzap — APPROVED** [review]
I am not able to test but looks good!

**Comment by dmitri-d** [comment]
* added a default value for ```blacklist_duration_minutes``` setting

**Comment by lzap** [comment]
Mind adding it to example yaml config file?

**Comment by dmitri-d** [comment]
We don't advertise this setting for dhcp_isc modules -- it was introduced "just in case", with the idea that shouldn't need to touch it. I think the same reasoning applies here as well.

**Comment by lzap** [comment]
Ok, I don't want to merge untested patches, but ping me if you need me to hit the button!

**Comment by dmitri-d** [comment]
@lzap: fwiw, I tested it in my windows VM -- seems to be working ok.

**Comment by lzap** [comment]
Good test coverage, I am pretty confident here. Thanks.

**Pull request merged**
