### PR TITLE
fixes #7297 - corrected name of DNS namespace in virsh error handlers

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by dmitri-d** [comment]
This looks good as a fix. Virsh provider should be refactored not to have dependencies on modules though. It looks like the only thing shared between dhcp and dns is Proxy::Virsh#virsh method?

**Comment by domcleal** [comment]
Yeah, I can move the error class into here/core to make more sense.

**Comment by dmitri-d** [comment]
I created a ticket for the refactoring: http://projects.theforeman.org/issues/7298. 

As an alternative to moving error classes into the core, we could move dns/dhcp-specific code into corresponding modules...

**Comment by domcleal** [comment]
Ah yes, I see what you mean now.  I'll have a closer look later and maybe just do the refactoring now.

**Comment by domcleal** [comment]
Refactoring's complete, I moved those specific DNS/DHCP methods back into the correct modules and used a Proxy::Virsh::Error class to raise errors from the shared code to the modules.

**Comment by dmitri-d** [comment]
looks good, will give a spin later today...

**Comment by dmitri-d** [comment]
merged at b32f2f7, ty @domcleal!

**Pull request closed without merging**
