### PR TITLE
refs #8625: add support for custom salt_puppetrun_cmd config parameter

### PR DESCRIPTION
**Pull request by charmms**
please test

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

Replaces #240

**Comment by logicminds** [comment]
What is a salt puppetrun?

**Comment by domcleal** [comment]
@logicminds Salt's a remote execution/config management tool.  Many people are using it to trigger Puppet remotely.

**Comment by dmitri-d** [comment]
merged in at a223066. Thanks, @charmms!

**Pull request closed without merging**
