### PR TITLE
Fixes #13219: force utf-8 external encoding on puppet classes

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
Argh, dhcp tests strike again. [test]

**Comment by domcleal** [comment]
Is this only on particular versions of Ruby, or certain locales?  I tried running under WEBrick on Ruby 1.9.3 and 2.1.0 with LANG set to UTF-8 and ISO-88591 but couldn't trigger the original bug.

**Comment by dmitri-d** [comment]
I think only earlier 1.9.3s had external encoding set to US-ASCII, any recent build should use UTF-8 instead. I could only trigger the issue when I modified the code to read puppet classes using US-ASCII external encoding.

**Comment by domcleal** [comment]
Okay, merged as 0a70eea, thanks @witlessbird.

**Pull request closed without merging**
