### PR TITLE
fixes #16009 - added support for native iPXE variant

### PR DESCRIPTION
**Pull request by korekhov**

### CODE REVIEW

**Comment by mmoll** [comment]
[test]

**Comment by korekhov** [comment]
works :)
 Konstantin Orekhov

```
  From: Michael Moll <notifications@github.com>
```

 To: theforeman/smart-proxy smart-proxy@noreply.github.com 
Cc: Konstantin Orekhov korekhov@yahoo.com; Author author@noreply.github.com
 Sent: Monday, August 8, 2016 2:29 PM
 Subject: Re: [theforeman/smart-proxy] fixes #16009 - added support for native iPXE variant (#451)

[test]—

**Comment by mmoll** [comment]
not according to Mr. Jenkins:

```
no implicit conversion of String into Array (TypeError)
/var/lib/workspace/workspace/test_proxy_develop_pr_core/puppet/4.4.0/ruby/2.3/modules/tftp/server.rb:135:in `+'
/var/lib/workspace/workspace/test_proxy_develop_pr_core/puppet/4.4.0/ruby/2.3/modules/tftp/server.rb:135:in `pxeconfig_file'
/var/lib/workspace/workspace/test_proxy_develop_pr_core/puppet/4.4.0/ruby/2.3/modules/tftp/server.rb:10:in `set'
/var/lib/workspace/workspace/test_proxy_develop_pr_core/puppet/4.4.0/ruby/2.3/test/tftp/tftp_server_test.rb:27:in `test_set'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testcase.rb:758:in `run_test'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testcase.rb:473:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/fixture.rb:267:in `block in create_fixtures_runner'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/fixture.rb:267:in `block in create_fixtures_runner'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/fixture.rb:267:in `block in create_fixtures_runner'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/fixture.rb:248:in `run_fixture'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/fixture.rb:283:in `run_setup'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testcase.rb:471:in `block in run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testcase.rb:470:in `catch'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testcase.rb:470:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testsuite.rb:124:in `run_test'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testsuite.rb:53:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testsuite.rb:124:in `run_test'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/testsuite.rb:53:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunner.rb:25:in `start'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/autorunner.rb:438:in `block in run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/autorunner.rb:494:in `change_work_directory'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/autorunner.rb:437:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit/autorunner.rb:62:in `run'
/usr/local/rvm/gems/ruby-2.3.0@test_proxy_develop_pr_core-2/gems/test-unit-3.2.1/lib/test/unit.rb:502:in `block (2 levels) in <top (required)>' 
```

**Comment by korekhov** [comment]
pushed a typo fix just now - can you re-test please?

**Comment by mmoll** [comment]
sure :)
[test]

**Comment by dmitri-d** [comment]
Merged as 24e943d. Thanks, @korekhov.

**Pull request closed without merging**
