### PR TITLE
Export arguments of parameterized classes

### PR DESCRIPTION
**Pull request by ofavre**
Export a `params` sub-object whose keys are the parameter names, along with their values, or `null` if the parameter is mandatory.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
testing by request from @ohadlevy: seems to work for me!

Obviously foreman doesn't show anything new about the detected classes, but it still correctly finds the new classes and deletes the old ones. Good stuff.

**Comment by ohadlevy** [comment]
do we have any idea which versions of puppet support the parser? which version is the oldest one that works?

**Comment by GregSutcliffe** [comment]
testing with wget seems good, returns things like (formatted for clarity):

{"dhcp":
  {"params":
    {"dnsupdatekey":null,
     "dhcp_monitor":true,
     "pxeserver":null,
     "interface":"NOTSET",
     "logfacility":"local7",
     "dnsdomain":null,
     "ntpservers":null,
     "interfaces":null,
     "pxefilename":null,
     "nameservers":null},
   "module":null,"name":"dhcp
  }
}

**Comment by GregSutcliffe** [comment]
I can probably try a few older versions tonight, but now I should get some work done :)

**Comment by ofavre** [comment]
Tests updated to work against Puppet 2.6

**Comment by ohadlevy** [comment]
merged! thanks @ofavre!!

**Pull request closed without merging**
