### PR TITLE
fixes #3712 - change develop versioning scheme to indicate next version

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by lzap** [comment]
ACK

But how are we going to put the datetags in it? By that I mean things like 20131122...

**Comment by domcleal** [comment]
Jenkins does that at the moment, just by inserting it before %{?dist} in the spec file when building.

**Comment by lzap** [comment]
OK

**Comment by domcleal** [comment]
Was merged as 133bac9fbafbea13121bf07262050f20377bd91e.

**Pull request closed without merging**
