### PR TITLE
Fixes #5712: Limit DHCP subnets for ISC if necessary

### PR DESCRIPTION
**Pull request by jimmidyson**
Implementation copied from 700e96b

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

@lzap could you review please?

**Comment by jimmidyson** [comment]
Not quite sure why this is failing as the errors are unrelated to the change made?

**Comment by domcleal** [comment]
Sorry about that, we found out today that a new mocha release broke on older patch versions of Ruby 2.0.0.  Puppet's just finished updating our build servers (https://github.com/theforeman/foreman-infra/commit/69d5d33f6abe354fc298ebe41833b90235e8a2bf), so this time it should pass: [test]

**Comment by jimmidyson** [comment]
Thanks @domcleal. We're running this patch in production & it's shaved over a minute off our provisioning time (before we had to increase the hard-coded timeout at https://github.com/theforeman/foreman/blob/develop/lib/proxy_api/resource.rb#L10, otherwise provisioning timed out).

**Comment by lzap** [comment]
On it, I had the issue opened already :-)

**Comment by lzap** [comment]
I can confirm it works for ISC DHCP, also when I give it empty list of subnets, it does not load them thus return IP addresses. +1

**Comment by domcleal** [comment]
Thanks @jimmidyson, merged as cabb60b for Foreman 1.5.1.

**Pull request closed without merging**
