### PR TITLE
moved facter loading into facter plugin descriptor

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
This works, although I wonder if handling 'facter' as a plugin dependency (i.e. putting it into 'facts' bundler group) is better.

**Comment by lzap** [comment]
Dmitri, we need a ticket, some better explanation.

I think this could be `Refs #7062` as I understand this as a definitive solution to that problem.

We do not want to have puppet and facter as bundler dependencies because we have users with bundler installations (not bundler_ext RPM/DEB) who want to use Puppet Enterprise or other Puppet distributions.

It works on my environment. I think we can merge, someone else?

**Comment by dmitri-d** [comment]
@lzap: created a ticket. Any chance you can merge this?

**Comment by lzap** [comment]
Yeah sorry, github does not send out pushes via email. Pushed as f655a4e - thanks @witlessbird !

**Pull request closed without merging**
