### PR TITLE
Pin public_suffix on RUBY_VERSION 2.0

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by mmoll — APPROVED** [review]

**Comment by dmitri-d** [comment]
Merged. Thanks, @ekohl!

**Comment by mmoll** [comment]
this is also needed for 1.16 and 1.15

**Comment by dLobatog** [comment]
http://ci.theforeman.org/job/systest_foreman/13546/console

**Comment by dLobatog** [comment]
I've just cherry-picked it to 1.15-stable and 1.16-stable, 405848a4378573c0bf824020fc31dde5011c90df
 and fd92ca73e

**Pull request merged**
