### PR TITLE
Fix 14882 (http://projects.theforeman.org/issues/14882)

### PR DESCRIPTION
**Pull request by elconas**
This one allows signing of DNS alt name requests

### CODE REVIEW

**Comment by ares** [comment]
ok to test or [test]

**Comment by dmitri-d** [comment]
Should we consider security issues associated with automatic enabling of alt-names in certificates? Perhaps this option should be requested explicitly in foreman ui/cli and passed on to smart-proxy? @domcleal, @brandonweeks -- thoughts?

**Comment by domcleal** [comment]
Yeah, it can't be enabled unilaterally - either via configuration and/or by request.

**Comment by elconas** [comment]
One addition, trusted extensions (https://docs.puppet.com/puppet/4.10/ssl_attributes_extensions.html#puppet-specific-registered-ids
( of certificate requests, (only visible via ```puppet cert list --verbose```) whould also be visible / shown. 

```
puppet cert list --verbose
  "testnode" (SHA256) 20:F5:18:7F:2A:5A:8C:3D:54:97:43:DF:9C:F1:6C:28:8E:D1:9B:AF:A0:E4:02:D1:04:D2:81:E4:D2:5D:7D:C6 (pp_cluster: "showcase", pp_environment: "development", pp_role: "webserver", pp_zone: "lan")
```

**Comment by dmitri-d** [comment]
@elconas: Are you planning on introducing a config option to enable/disable this feature?

**Comment by dmitri-d** [comment]
Alternatively, you could pass a request parameter to enable signing of alt name requests.

**Comment by ekohl** [comment]
I wonder if a list of allowed names would make sense.

**Comment by dmitri-d** [comment]
@elconas: are you planning to continue the work on this PR?

**Comment by elconas** [comment]
Another similar problem is that if you have trusted extension enabled (see https://docs.puppet.com/puppet/4.10/ssl_attributes_extensions.html) those are also not visible in the foreman gui):

```
puppet cert list --verbose cert.bla
  "cert.bla" (SHA256) CB:4D:11:62:74:1D:77:BE:E7:8E:A8:3D:62:ED:D1:C9:F2:70:EE:FE:ED:5F:1B:1F:6E:1A:61:4C:A9:C6:07:DC (alt names: "DNS:cert.bla", "DNS:devvm.vagrant.local", pp_cluster: "xxx", pp_environment: "development", pp_role: "yyyy", pp_zone: "lan", subjectAltName:)
```
So addressing this issue properly whould mean: 
* Provide API Users a way to retrieve certificate extensions - short *make the information available*
* Provide Foreman Users a way to display extended certificate attributes (e.g. trusted facts and dns alt names) in the GUI and then assuming if the user clicks "sign" that he has verified this information (as of now). - short *make the info visible*

As I am not a Ruby on Rails developer, I am not able to provide a proper fix in an acceptable time :(

**Comment by gittygoo** [comment]
Much needed feature, manually patched this on a test server and seems to be working fine, with a few additions (showing the SAN's on the foreman cert table) this would be perfect. Thanks for doing this!

**Comment by lzap** [comment]
Thanks for the patch so far, this needs to be a configurable option, possibly with a list of hostnames as folks suggest. Please rebase, add config option, tests and reopen or file a new PR if you want this functionality. I am closing for now.

**Pull request closed without merging**
