### PR TITLE
Fix tests for 1.9. & Fix deprecation warnings

### PR DESCRIPTION
**Pull request by GregSutcliffe**

### CODE REVIEW

**Comment by ohadlevy** [comment]
I'm assuming this all pass on 1.87 too?

**Comment by GregSutcliffe** [comment]
Jenkins is running 1.8.7. Locally, I've tested with 1.9.3 as well. This PR doesn't fix all the tests, it just sorts out the things that block them from running at all. I currently get ~30 failures, mostly in the BMC tests.

**Comment by GregSutcliffe** [comment]
The tests now all pass on ruby1.9 and ruby1.8:

http://ci.theforeman.org/view/Core/job/test_proxy_develop/34/testReport/

**Comment by ohadlevy** [comment]
squashed, merged with minor change - thanks @GregSutcliffe!

**Pull request closed without merging**
