### PR TITLE
Fixes #25825 - fixed BMC SSH config names

### PR DESCRIPTION
**Pull request by lzap**
SSIA + typos in SSH BMC module example config

### CODE REVIEW

**Comment by lzap** [comment]
Someone? @ekohl perhaps? This is a trivial one thanks!

**Review by ekohl — APPROVED** [review]
From reading the code this does appear to be correct, but it also means https://github.com/theforeman/puppet-foreman_proxy/commit/668eb6525d0f246e4fbdddfecf159ad4de23665e#diff-4cec27937c8aef24f2e4df145925452cR8 is wrong and needs an update. Since it's unreleased there's still time but it'd be good to get it in before 1.21.

**Comment by ekohl** [comment]
https://theforeman.org/manuals/1.20/index.html#4.3.3BMC will also need an update if this is incorrect.

**Comment by lzap** [comment]
Done thanks.

**Comment by lzap** [comment]
WAIT

Looks like puppet codebase also has this prefixed version, I am gonna change the code rather than this.

https://github.com/theforeman/puppet-foreman_proxy/commit/668eb6525d0f246e4fbdddfecf159ad4de23665e#diff-4cec27937c8aef24f2e4df145925452cR8

**Comment by lzap** [comment]
I rebased the PR, now the config keys are actually correct.

**Comment by ekohl** [comment]
The installer side hasn't been released yet. I can be ok with this change because the parameters only affect the SSH provider, but it is a breaking change.

**Comment by lzap** [comment]
I can do migration if needed but I think it is not worth the effort.

**Comment by lzap** [comment]
FYI I fixed the failing test in another PR.

**Review by tbrisker — APPROVED** [review]
Thanks @lzap !

**Comment by tbrisker** [comment]
1.21- b708da3
do we need to cherry pick this to 1.20 as well?

**Comment by lzap** [comment]
Thanks, I don't think so. Again, not in wide use. I am probably the only user when testing BMC API :-)

**Pull request merged**
