### PR TITLE
Fixes #9063 - Revert pinning of Rack to < 1.6

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Ruby 1.8 is not supported by -proxy now anyway.

**Comment by domcleal** [comment]
Merged, thanks @mmoll.

**Comment by dLobatog** [comment]
Seems like now it's asking for Ruby 2.2 at least because it tries to get the latest version of Rack.

**Comment by mmoll** [comment]
argh, this needs a `< 2` added, but I don't have time the next days...

**Comment by mmoll** [comment]
or maybe if it works with 2.x, that <1 only for Ruby <2.2

**Pull request merged**
