### PR TITLE
fix handling of multiple module paths

### PR DESCRIPTION
**Pull request by luxflux**
Replace every occurrence of $confdir, not only the first one

### CODE REVIEW

**Comment by ohadlevy** [comment]
@luxflux looks good to me, @domcleal ?

**Comment by domcleal** [comment]
+1 to merge.

**Comment by ohadlevy** [comment]
@domcleal do you know if we have an open ticket for this one?

**Comment by domcleal** [comment]
Not that I'm aware of.  We've got a very similar issue in [#2099](http://theforeman.org/issues/2099) where $confdir's only interpolated if $environment is present (due to how the conditionals there are structured).  We could bundle them together.

**Comment by dcleal** [comment]
Don't think you meant to send this to me....
- Dave Cleal

**Pull request closed without merging**
