### PR TITLE
Fixes #12136: in puppet_proxy load only dependencies and concrete implementation classes that are required by the configuration

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by domcleal** [comment]
Could you shorten the first line of the commit message please?  If you can keep it to 72 chars, with anything else going into line 3 and beyond, it'd work better with git clients.

**Comment by dmitri-d** [comment]
@domcleal: done

**Comment by domcleal** [comment]
The module no longer appears to load, it's getting an exception that you can see here:

<pre>
I, [2015-11-10T12:15:49.787360 #8476]  INFO -- : 'puppet' settings were initialized with default values: :puppet_ssl_ca: /var/lib/puppet/ssl/certs/ca.pem, :salt_puppetrun_cmd: puppet.run, :use_cache: true
I, [2015-11-10T12:15:49.788693 #8476]  INFO -- : Initializing from Puppet config file: /home/dcleal/.puppet/puppet.conf
E, [2015-11-10T12:15:49.829200 #8476] ERROR -- : Couldn't enable plugin puppet: uninitialized constant Proxy::Puppet::DependencyInjection::Wiring
D, [2015-11-10T12:15:49.829301 #8476] DEBUG -- : uninitialized constant Proxy::Puppet::DependencyInjection::Wiring:/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:7:in `<class:Dependencies>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:5:in `<module:DependencyInjection>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:4:in `<module:Puppet>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:3:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_plugin.rb:20:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_plugin.rb:20:in `block in <class:Plugin>'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/pluggable.rb:33:in `instance_eval'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/pluggable.rb:33:in `after_activation'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:137:in `configure_plugin'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `block in configure_loaded_plugins'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `each'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `configure_loaded_plugins'
/home/dcleal/code/foreman/smart-proxy/lib/launcher.rb:101:in `launch'
bin/smart-proxy:6:in `<main>'
</pre>

**Comment by dmitri-d** [comment]
@domcleal: fixed.

**Comment by domcleal** [comment]
Thanks, it now loads but doesn't seem to fix the bug for me.  I still get an error as class_scanner_eparser is loaded from the top of puppet_class.rb:

<pre>
D, [2015-11-11T08:53:41.988277 #6524] DEBUG -- : cannot load such file -- rgen/ecore/ecore:/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops/containment.rb:3:in `require'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops/containment.rb:3:in `<top (required)>'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops.rb:22:in `require'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops.rb:22:in `<module:Pops>'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops.rb:12:in `<module:Puppet>'
/home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/pops.rb:1:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/class_scanner_eparser.rb:6:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/class_scanner_eparser.rb:6:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_class.rb:2:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_class.rb:2:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/class_scanner.rb:1:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/class_scanner.rb:1:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:15:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:15:in `puppet_parser_class'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:34:in `<class:Dependencies>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:5:in `<module:DependencyInjection>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:4:in `<module:Puppet>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/dependency_injection/dependencies.rb:3:in `<top (required)>'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_plugin.rb:21:in `require'
/home/dcleal/code/foreman/smart-proxy/modules/puppet_proxy/puppet_plugin.rb:21:in `block in <class:Plugin>'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/pluggable.rb:33:in `instance_eval'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/pluggable.rb:33:in `after_activation'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:137:in `configure_plugin'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `block in configure_loaded_plugins'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `each'
/home/dcleal/code/foreman/smart-proxy/lib/proxy/plugin.rb:28:in `configure_loaded_plugins'
/home/dcleal/code/foreman/smart-proxy/lib/launcher.rb:102:in `launch'
bin/smart-proxy:6:in `&lt;main>'
</pre>

**Comment by domcleal** [comment]
By the way, this is also quite easy to reproduce on a bundler/gem installation by installing Puppet 3.x, ensuring the environment API is off and also running something like `mv /home/dcleal/.rvm/gems/ruby-2.1.0@proxy/gems/puppet-3.8.4/lib/puppet/vendor/rgen /tmp/` (equivalent to how rgen's optional).

**Comment by dmitri-d** [comment]
@domcleal: fixed.

**Comment by domcleal** [comment]
Works well.  Thanks @witlessbird, merged as 7cbe47a.

**Pull request closed without merging**
