### PR TITLE
Fixes #37631 - Allow nested data structures as request parameters

### PR DESCRIPTION
**Pull request by nadjaheitmann**
If you go to the Host Registration form in foreman and choose a smart-proxy and multiple repositories, the registration fails with an internal server error. This is due to the new format of the repo_data in the API which supports an array of repository and corresponding gpg key pairs (https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v2/registration_controller.rb#L29).

### CODE REVIEW

**Review by sbernhard — APPROVED** [review]
LGTM. Thanks!

**Review by m-bucher — APPROVED** [review]
Nice, makes sense to use an existing method to build the query-string.

**Comment by sbernhard** [comment]
the "query_string" method is used from "create_get" and "create_post" which are tested in https://github.com/theforeman/smart-proxy/blob/beb0147354797bd1c2fe1f74cb12a43476d2dfce/test/request_test.rb#L10 

Can you please add more tests to make sure this method works as expected.

**Comment by sbernhard** [comment]
@adamruzicka Any concerns that I merge this?

**Comment by adamruzicka** [comment]
None from me, looks good

**Pull request merged**
