### PR TITLE
The path to puppetca is /opt/puppet/sbin for PE.

### PR DESCRIPTION
**Pull request by apenney**

### CODE REVIEW

**Comment by skottler** [comment]
:+1:

**Comment by domcleal** [comment]
We should keep both sbin and bin here I think, in anticipation of PE shipping Puppet 3 and going back to the "puppet" binary only.  Otherwise :+1:, @ohadlevy can probably fix that on merge.

[test]

**Comment by logicminds** [comment]
This should contain both since pe version 1 uses bin.  It would be better to let the user define in config along with these default parameters.

**Comment by ohadlevy** [comment]
fixed with @domcleal suggestion at 32d9749

**Pull request closed without merging**
