### PR TITLE
fixes #37486 - Request BMC using Redfish without reaching sessions limit

### PR DESCRIPTION
**Pull request by neomilium**
As described in issue, sessions limit is reach quickly when using current _Redfish_ implementation.

Here, redefining the `RedfishClient::Root#session_path` allow us to change the way `redfish_client` process the authentication in order to force to use only `basic_auth` and never retrieve a session that Foreman never closes.

Issue: https://projects.theforeman.org/issues/37486

### CODE REVIEW

**Comment by evgeni** [comment]
ok to test

**Comment by neomilium** [comment]
I just force-pushed to fix rubocop offence related to comment.

**Comment by evgeni** [comment]
Is this the same issue as described in https://community.theforeman.org/t/redfish-leaks-connections-and-results-in-many-active-connections-to-bmc-interface/30559?

**Comment by evgeni** [comment]
cc @dgoetz @laugmanuel @gardar

**Comment by laugmanuel** [comment]
Without really looking into it any deepter, it looks plausible.
However, I can't test it as we stopped using the BMC feature in Foreman altogether.

**Comment by laugmanuel** [comment]
cc @ochnerd, @thomas-merz

**Comment by ekohl** [comment]
I'd consider an alternative and that is cleaning up sessions by logging out. https://github.com/theforeman/smart-proxy/pull/896 is that. I'm not sure yet what's best. Perhaps avoiding sessions in the first place fits the model better, depending on how many API calls within a session we perform.

A more complex approach would be to reuse connections, but I'd be hesitant given the complexity of that.

**Comment by gardar** [comment]
Looks good at first glance, I should be able to test this next week

**Comment by neomilium** [comment]
@ekohl About how many call we made, I can say that a simple look on host's _Overview_ page took one session token while browsing to _BMC_ tab in legacy UI took 5 sessions.

As in iDRAC/8 there are 8 session slots, a regular browsing can easily reach the limit even the sessions stored in iDRAC expire automatically within hours.
Note: I did not count it exactly nor found this delay in iDRAC's web UI, just saw that an iDRAC with all sessions allocated will be reachable after a night.

**Comment by neomilium** [comment]
> Is this the same issue as described in https://community.theforeman.org/t/redfish-leaks-connections-and-results-in-many-active-connections-to-bmc-interface/30559?

Yes, exactly.

**Comment by ekohl** [comment]
@neomilium It's Foreman -> Smart Proxy -> BMC. With https://github.com/theforeman/smart-proxy/pull/896 one API call to the Smart Proxy would be a single session. So if that call performs multiple requests, a single session **could** be a benefit, but if basic auth is just as fast then your PR is preferred (because my session cleanup could fail while your will never open a session).

**Comment by neomilium** [comment]
> [...] but if basic auth is just as fast then your PR is preferred (because my session cleanup could fail while your will never open a session).

I show some benchmarks at #896

**Review by ekohl — CHANGES_REQUESTED** [review]
@neomilium my patch was merged and 0.6.0 was released. Could you rebase your patch to use the new parameter and raise the minimum version to 0.6.0?

**Comment by neomilium** [comment]
@ekohl Done. Thank you.

**Review by ekohl — APPROVED** [review]
Thanks!

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/11028 & https://github.com/theforeman/foreman-packaging/pull/11029 update the dependency.

**Pull request merged**
