### PR TITLE
Fixes #10015 - FreeIPA realm-proxy permissions do not allow for...

### PR DESCRIPTION
**Pull request by Thubo**
removing a DNS record at time of host delete

Changes:
- Add permission 'System: Read DNS Entries' to permission system v2

### CODE REVIEW

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
@stbenjam could you have a look here?

**Comment by stbenjam** [comment]
Looks good to me :+1:

**Comment by dmitri-d** [comment]
@stbenjam: I assume this can be merged then? Out of curiosity, where are these permissions documented?

**Comment by stbenjam** [comment]
>  I assume this can be merged then? 

Yup, good to merge.

> Out of curiosity, where are these permissions documented? 

They're not, really.  It was trial and error with the assistance of the FreeIPA team to come up with the minimum permissions we needed.

The V1 permissions include Read DNS entries, looks like it was missed when we included support for V2.

**Comment by dmitri-d** [comment]
@stbenjam: cheers. Could you write a short wiki page about these permissions when you have a chance? Not sure whom else I can ask about this...

**Comment by dmitri-d** [comment]
Merged as a28340b. Thanks, @Thubo.

**Pull request closed without merging**
