### PR TITLE
Fixes #13346 - use of .each_line on array

### PR DESCRIPTION
**Pull request by helge000**
A version of #365 against develop

I could not test this one, but looking though the code the essentials did not change.

### CODE REVIEW

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
Tested, looks good. Waiting for the tests to finish.

**Comment by helge000** [comment]
@witlessbird sadly not as simple as in 1.10-stable. 
At fist glance, the provider seems in some transitional state ;)

I've done some testing (see below); the issue is somewhere in the new [parse functions](https://github.com/theforeman/smart-proxy/blob/develop/modules/dhcp_native_ms/dhcp_native_ms_main.rb#L249). Rigtht now I find it hard to pinpoint the ominous sting; so maybe just update the test case? At the very least the no method error is reproducible.

```
Error: test_parse_standard_and_vendor_options(DHCPServerMicrosoftTest): NoMethodError: undefined method `each' for #<String:0x000000025b74d8>
/home/daniel/GitRepos/smart-proxy/modules/dhcp_native_ms/dhcp_native_ms_main.rb:256:in `parse_options'
/home/daniel/GitRepos/smart-proxy/test/dhcp_ms_native/server_ms_test.rb:154:in `test_parse_standard_and_vendor_options'
     151:                 Option Element Value = /vol/solgi_5.10/sol10_hw0910
     152: Command completed successfully.
     153: EOL
  => 154:     parsed = @server.parse_options(to_parse)
     155:     assert_equal 3, parsed.size
     156:     assert_equal "<SPARC-Enterprise-T5120>", parsed[:vendor]
     157:     assert_equal "brslcs25", parsed[:hostname]
```

**Comment by dmitri-d** [comment]
@helge000: there are a few more tests (the first one is here: https://github.com/theforeman/smart-proxy/blob/develop/test/dhcp_ms_native/server_ms_test.rb#L203) that use multiline strings, which now need to be converted to arrays (same way as you did at the top). You can check if tests run green by executing `bundle exec rake test`.

**Comment by helge000** [comment]
@witlessbird Right! It was the test case in the end... successfully tested `bundle exec rake test TEST=test/dhcp_ms_native/server_ms_test.rb`  with ruby 1.9.3 and ruby 2.1

**Comment by dmitri-d** [comment]
[test]

**Comment by dmitri-d** [comment]
merged in at 35d9fb3. Thanks, @helge000.

**Comment by dmitri-d** [comment]
@helge000: I wanted to ask you not to insert your signature in commit messages: the commit is merged under your name and email (that you used during git setup), making this information redundant.

**Comment by helge000** [comment]
@witlessbird No problem, I've already removed it from my `.gitconfig` (witch predates github, at least by timestap ;)

**Comment by domcleal** [comment]
Regarding the backport to 1.10-stable, I've marked the Redmine ticket for the 1.10.2 release and I'll take care of cherry picking it closer to the time (http://projects.theforeman.org/projects/foreman/wiki/Foreman_110_Schedule).  Thanks for the patch @helge000!

**Pull request closed without merging**
