### PR TITLE
Add powerdns to dns proxy

### PR DESCRIPTION
**Pull request by crazed**
This works for basic PowerDNS functionality with MySQL as a backend

### CODE REVIEW

**Comment by ohadlevy** [comment]
@crazed this is awesome! I'll try to review tomorrow, sadly I dont have access to powerdns instance, were you able to validate that it works on bind as well?

thanks!

**Comment by crazed** [comment]
Thanks! No I couldn't test bind and didn't see any tests. I'm in the
opposite boat, no bind server to test with currently.

**Comment by anthonysomerset** [comment]
I'm currently in the process of writing an interface to PointHQ for the smart-proxy for DNS, i think the whole ability to select different DNS providers is a great thing

at the moment to avoid later merge issues i'm somewhat held back by this pull request for the select DNS backend logic - is it possible that we could do a seperate pull request with just the first commit: https://github.com/crazed/smart-proxy/commit/18ccc00c407126228c801926c3297ca0d4d71df7 to allow for further DNS smart-proxy services to be integrated

**Comment by lzap** [comment]
This needs a rebase, we changed smart proxy codebase to plugin architecture. Then @ohadlevy are you still able to review? :-)

**Comment by brianczapiga** [comment]
I'm working in a new environment with a bind server only. Trying to get PowerDNS installed as standard in this environment. Once done, I'll work on the plugin. :)

**Comment by ekohl** [comment]
It may be interesting to know that 3.4 will have a REST API. See https://github.com/PowerDNS/pdnsapi for more information.

**Comment by dgagnon** [comment]
Was this ever implemented using a plugin ?

**Comment by ekohl** [comment]
@dgagnon No, this was written a long time before the smart-proxy ever had plugins.

**Comment by domcleal** [comment]
The Smart Proxy's DNS module can now be extended by plugins, thanks to #7008.  This would be a great way to start developing this feature if anybody's interested.

Here are some useful links:
- http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Smart-Proxy_Plugin - developer information
- https://github.com/theforeman/smart_proxy_dns_plugin_template - a near-working template to create a new DNS provider
- https://github.com/theforeman/smart_proxy_dns_route53 - a working example adding AWS Route53 support

**Comment by ekohl** [comment]
Totally untested (and attribution): https://github.com/ekohl/smart_proxy_dns_powerdns

**Comment by dmitri-d** [comment]
Haven’t looked at the code much, but this:
https://github.com/ekohl/smart_proxy_dns_powerdns/blob/master/lib/smart_proxy_dns_powerdns/dns_powerdns_main.rb#L33
is
open for sql injection…

-d

**Comment by ekohl** [comment]
@witlessbird that was already present in the original code, but I agree and noticed it too.

**Comment by ekohl** [comment]
https://github.com/theforeman/smart_proxy_dns_powerdns now exists so I think this can be closed.

**Comment by dmitri-d** [comment]
closing, as a standalone plugin for power dns exists now: https://github.com/theforeman/smart_proxy_dns_powerdns

**Pull request closed without merging**
