### PR TITLE
Fixes #5907 - Look at all records when suggesting IPs

### PR DESCRIPTION
**Pull request by GregSutcliffe**
has_mac? has two arguments now....

### CODE REVIEW

**Comment by lzap** [comment]
So you want to close this one, Greg?

**Comment by domcleal** [comment]
This one should be merged straight to develop as it fixes a bug by itself, the PR to wb shouldn't replace it.

**Comment by GregSutcliffe** [comment]
Agreed, it should be merged so @witlessbird can rebase on it - I included it in stuff I was doing with him because I wanted to check end-to-end provisioning would work correctly

**Comment by GregSutcliffe** [comment]
@lzap ping?

**Comment by lzap** [comment]
Hmm it does not work with virsh provider. Investigating with ISC.

**Comment by lzap** [comment]
Hmmm I dont have the `:all` type.

**Comment by lzap** [comment]
It gives me random, although I request for a already allocated MAC address:

```
D, [2014-05-30T12:48:18.043245 #23463] DEBUG -- : Loading subnets for {:virsh_network=>"default"}
D, [2014-05-30T12:48:18.043620 #23463] DEBUG -- : /usr/bin/sudo /usr/bin/virsh net-dumpxml default 2>&1
D, [2014-05-30T12:48:18.094992 #23463] DEBUG -- : Added 192.168.122.0/255.255.255.0 to {:virsh_network=>"default"}
D, [2014-05-30T12:48:18.095654 #23463] DEBUG -- : Loading subnet data for 192.168.122.0/255.255.255.0
D, [2014-05-30T12:48:18.106976 #23463] DEBUG -- : Added 192.168.122.237 / 52:54:01:e2:fa:f1 to 192.168.122.0/255.255.255.0
D, [2014-05-30T12:48:18.107143 #23463] DEBUG -- : Added 192.168.122.25 / 52:54:01:71:df:cd to 192.168.122.0/255.255.255.0
D, [2014-05-30T12:48:18.107304 #23463] DEBUG -- : Added 192.168.122.6 / 52:54:01:1f:b7:b4 to 192.168.122.0/255.255.255.0
D, [2014-05-30T12:48:18.107477 #23463] DEBUG -- : Added 192.168.122.10 / aa:bb:cc:dd:dd:dd to 192.168.122.0/255.255.255.0
D, [2014-05-30T12:48:18.107608 #23463] DEBUG -- : Lazy loaded 192.168.122.0/255.255.255.0 records
D, [2014-05-30T12:48:18.107730 #23463] DEBUG -- : trying to find an ip address, we got {:from=>"192.168.122.10", :to=>"192.168.122.200", :mac=>"52:54:01:e2:fa:f1"}
D, [2014-05-30T12:48:18.110822 #23463] DEBUG -- : trying to find an ip address, we got {:from=>"192.168.122.10", :to=>"192.168.122.200", :mac=>"52:54:01:e2:fa:f1"}
D, [2014-05-30T12:48:18.114165 #23463] DEBUG -- : Searching for free IP - pinging 192.168.122.18
D, [2014-05-30T12:48:20.121595 #23463] DEBUG -- : Found free IP 192.168.122.18 out of a total of 189 free IPs
::1 - - [30/May/2014 12:48:20] "GET /dhcp/192.168.122.0/unused_ip?mac=52:54:01:e2:fa:f1&from=192.168.122.10&to=192.168.122.200 HTTP/1.1" 200 23 2.0794
localhost - - [30/May/2014:12:48:18 CEST] "GET /dhcp/192.168.122.0/unused_ip?mac=52:54:01:e2:fa:f1&from=192.168.122.10&to=192.168.122.200 HTTP/1.1" 200 23
- -> /dhcp/192.168.122.0/unused_ip?mac=52:54:01:e2:fa:f1&from=192.168.122.10&to=192.168.122.200
```

**Comment by lzap** [comment]
It works fine, I had my test IP outside of my valid range :-) OMG No :coffee: today.

**Comment by lzap** [comment]
Pushed as ee9b08d for Foreman 1.6. Thanks!

**Pull request closed without merging**
