### PR TITLE
Fixes #12597: remove extraneous method definition in the DNS API tests

### PR DESCRIPTION
**Pull request by sodabrew**
http://projects.theforeman.org/issues/12597

### CODE REVIEW

**Comment by sodabrew** [comment]
@witlessbird Could you take a look at the test failure? I removed the extra method definition, which seems to be blocking this test before, and now that it is executing it fails. Was originally added in 42b958156808eb2a16bd895863b196fca8f2977d

```
   def test_delete_returns_error_if_value_is_missing
     delete '/'
     assert_equal 400, last_response.status
   end
```

Smart Proxy is returning 404 in this case. That seems correct to me?

**Comment by domcleal** [comment]
Oops, sorry about the failure, I should've noticed that in the review and also re-run tests with the new rubocop.

Either 404 or 400 seems reasonable to me.  Returning 400 as dns_api.rb intends would require changing the route to `/:value?`, but since the value _isn't_ actually optional (that's the point of the nil check) then returning 404 seems OK as the route `DELETE /` isn't valid.  I'd say removing the check and expecting 404 is probably OK.

**Comment by dmitri-d** [comment]
I'm not sure why it's returning 404 (this implies parameter validator isn't catching that the required parameter is missing), let me look into this. I think I favour returning a 400, but 404 seems reasonable too.

**Comment by domcleal** [comment]
> I'm not sure why it's returning 404 (this implies parameter validator isn't catching that the required parameter is missing)

The route doesn't match.  It's defined as `delete '/:value'` which implies :value must be present.  Adding a `?` would make the value optional, which would trigger the validator.

**Comment by domcleal** [comment]
> Adding a ? would make the value optional, which would trigger the validator.

A thought - it looks like all other delete routes are the same, so we probably shouldn't change just this one.

**Comment by dmitri-d** [comment]
Of course, always forget this bit. Agree that the behaviour in this case should  match other 'delete' calls.

**Comment by sodabrew** [comment]
@witlessbird I merged in your further change - thank you! I will be offline a lot this week for the US Thanksgiving holiday. Please let me know if I need to squash on this branch, if it it'll get taken care of in a squash-cherry-pick to develop?

**Comment by dmitri-d** [comment]
@sodabrew: could you squash the commits please?

**Comment by sodabrew** [comment]
ok, got me while I'm still sitting at the desk!

**Comment by dmitri-d** [comment]
merged in bef9bee. Thanks, @sodabrew!

**Pull request closed without merging**
