### PR TITLE
Fixes #7862 - Upgrade rubocop version

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by dLobatog** [comment]
:+1: same as in core. Let's coordinate updates when you're back online in #theforeman-dev

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
If the build passes, we should probably merge this to fix develop.

**Comment by dLobatog** [comment]
@daviddavis Thanks, I'm merging this.

**Comment by dLobatog** [comment]
Merged as https://github.com/theforeman/smart-proxy/commit/8aa4e0f94bdb0aaff7fc61f95fd55b06a72e98c1 , thanks again @daviddavis !

**Pull request closed without merging**
