### PR TITLE
fixes #7660: fixes first bunch of rubocop warnings

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by daviddavis** [comment]
@witlessbird I updated rubocop but I'd like to get this fix in. I'll take a look at updating this PR myself so we can get it merged. My apologies.

**Comment by dmitri-d** [comment]
@daviddavis: was going to redo this today. Unless you are _very_ keen on fixing it yourself :P

**Comment by daviddavis** [comment]
No, go for it. Was going to do it this weekend or next week.

**Comment by daviddavis** [comment]
Let me know when you've fixed it and I'll review.

**Comment by dmitri-d** [comment]
will do!

**Comment by dmitri-d** [comment]
closing. instead see https://github.com/theforeman/smart-proxy/pull/225.

**Pull request closed without merging**
