### PR TITLE
Fixes #33756 - Require 'templates' for 'registration' module

### PR DESCRIPTION
**Pull request by stejskalleos**
Related to https://github.com/theforeman/foreman/pull/8855

### CODE REVIEW

**Comment by ekohl** [comment]
Could you open a new Redmine issue for this? We don't allow cross project refs.
The test failure is also related and shows exactly what is supposed to happen. Perhaps you can have a test to assert the failure and a test where templates is enabled and assert success?

Edit: this should probably also be reflected in the installer. There it should either error out early or automatically enable the feature.

**Review by ekohl — COMMENTED** [review]
Could you also add a test case where templates isn't loaded and assert that it fails? Other than that :+1:

**Comment by stejskalleos** [comment]
> Could you also add a test case where templates isn't loaded and assert that it fails? Other than that +1

Test added

**Review by ekohl — APPROVED** [review]
Thanks!

Edit: tests are still running.

**Pull request merged**
