### PR TITLE
Add support for 64-bit MAC addresses, fixes #6341

### PR DESCRIPTION
**Pull request by treydock**
Expands validation of MAC addresses to include 64bit MAC addresses.  This is related to theforeman/foreman#1470.

### CODE REVIEW

**Comment by treydock** [comment]
[test]

**Comment by dmitri-d** [comment]
lgtm.

**Comment by domcleal** [comment]
There's also a custom MAC validator over at modules/tftp/tftp_api.rb:11, would you mind updating it too please?

**Comment by treydock** [comment]
@domcleal I've updated the PR to use a valid_mac? method that can be reused in other places (including the tftp_api).  I also added a few tests for the Proxy::TFTP::Api class.  What's added was just enough to test the MAC address validation and for me to try my hand at Rack unit tests.

**Comment by domcleal** [comment]
Great tests, thanks!

Merged as 5f46b1b for Foreman 1.6.0 - cheers @treydock.

**Pull request closed without merging**
