### PR TITLE
Fixes #11090: Fix README filename in the gemspec

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
I think this fixes the following warning:

smart_proxy at /home/ekohl/.gem/ruby/bundler/gems/smart-proxy-d905c67c1067 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["README"] are not files

**Comment by domcleal** [comment]
:+1:, due to c08eb9a80.

**Comment by dmitri-d** [comment]
Good catch.

**Comment by dmitri-d** [comment]
@ekohl: could you update the commit message to: `Fixes #11090: fixed README filename in the gemspec`

**Comment by ekohl** [comment]
@witlessbird done

**Comment by dLobatog** [comment]
Merged as 00c92ddb43d9d69b162188b0eefe033fb04d4684, thanks @ekohl !

**Pull request closed without merging**
