### PR TITLE
fixes #6722 - correct require for kerberos utilities

### PR DESCRIPTION
**Pull request by domcleal**
#194 should fix the test failures

### CODE REVIEW

**Comment by lzap** [comment]
It failed...

**Comment by domcleal** [comment]
@lzap see the PR description, and subsequent PR

**Comment by lzap** [comment]
Tests are green on my laptop.

**Comment by lzap** [comment]
Was this failing on RHEL6 as well? Should we test RHEL6?

**Comment by domcleal** [comment]
Any OS if you use that DNS provider.

**Comment by domcleal** [comment]
[test]

**Comment by dmitri-d** [comment]
tested; looks good to me.

**Comment by dmitri-d** [comment]
merged, thanks @domcleal!

**Pull request closed without merging**
